### ISSUE TITLE
안녕하세요 기능 제안입니다

### ISSUE THREAD

**Issue by tmdgkr07** [remote-kakao/remote-kakao#3]
안녕하세요 리모트 카카오덕분에 편하게 카카오톡 주식 챗봇을 만들어 사용중입니다.

근데 딱 1가지 아쉬운점이 있습니다  채팅세션이 대략 300개정도 밖에 유지 되지 않는다는것입니다.

예를 들어 아침 9시마다 채팅방에 특정글을 올려주고싶은데 어떤방( 최근 채팅 300개 이내에 포함된 방)은 전송이되고 어떤 방은 undefined 오류가 뜨면서 전송되지 않습니다 한번이라도 채팅을 했던방은 세션을 유지시켜주는 기능이 있었으면 좋겠습니다...

**Comment by dn1t** [comment]
remote-kakao v1의 채팅 세션은 메신저봇R에서 관리해서 제가 어떻게 할 수 있는 방법이 없었는데, 현재 개발중인 v2의 [core-client](https://github.com/remote-kakao/core-client)에선 세션을 직접 관리하도록 변경했습니다. 다만 Rhino 위의 Map에 세션이 저장되기 때문에 만약 Rhino Map의 구현에 아이템 개수나 용량의 제한이 존재한다면 해당 제한에 구애받을 수 있고, 기존 메신저봇R의 Java HashMap을 이용한 구현에 비해 성능은 조금 떨어질 수 있습니다.
